AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  04-powertools

  Sample SAM application that showcases the use of powertools

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 3
    MemorySize: 128
    Environment:
      Variables:
        POWERTOOLS_SERVICE_NAME: Demo04
        LOG_LEVEL: INFO
        POWERTOOLS_METRICS_NAMESPACE: SampleApplication

Resources:
  Demo04Lambda:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: app/
      Handler: app.lambda_handler
      Runtime: python3.9
      Architectures:
        - x86_64
      Events:
        Demo04Api:
          Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            Path: /my-endpoint
            Method: get

Outputs:
  # ServerlessRestApi is an implicit API created out of Events key under Serverless::Function
  # Find out more about other implicit resources you can reference within SAM
  # https://github.com/awslabs/serverless-application-model/blob/master/docs/internals/generated_resources.rst#api
  Demo04Api:
    Description: "API Gateway endpoint URL for Prod stage for Hello World function"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/my-endpoint/"
  Demo04Lambda:
    Description: "Hello World Lambda Function ARN"
    Value: !GetAtt Demo04Lambda.Arn
  Demo04LambdaIamRole:
    Description: "Implicit IAM Role created for Hello World function"
    Value: !GetAtt Demo04LambdaRole.Arn
